version: 2
jobs:
  build:
    docker:
      #      - image: ubuntu:16.04
      - image: rikorose/gcc-cmake:latest
      #    working_directory: /meaningless
    steps:
      - checkout
      #      - run:
      #    name: cmake
      #    command: cmake .
      #- run:
      #    name: make
      #    command: make

      - run:
          name: build
          command: mkdir build && cd build && cmake .. && make
      - run:
          name: run
          command: ./build/hello_world
