version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: /build

    steps:
      - checkout
      - run:
          name: cmake
          command: cmake ..
      - run:
          name: make
          command: make

      - run:
          name: run
          command: ./hello_world
