version: 2
jobs:
  build:
    docker:
      #      - image: ubuntu:16.04
      #      - image: rikorose/gcc-cmake:latest
      - image : koobh/iip_demo_env:latest
    steps:
      - checkout
      - run:
          name: build
          command: mkdir build && cd build && cmake .. && make
      - run:
          name: run
          command: ./build/hello_world
