version: 2
jobs:
  build:
    docker:
      #      - image: ubuntu:16.04
      - image: rikorose/gcc-cmake:latest
    working_directory: /meaningless
    steps:
      - checkout
      - run:
          name: create build
          command: mkdir build
      - run:
          name: move to build
          command: cd build
      - run:
          name: cmake
          command: cmake ..
      - run:
          name: make
          command: make

      - run:
          name: run
          command: ./hello_world
